/*
 * generated by Xtext 2.11.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RobotStandaloneSetup extends RobotStandaloneSetupGenerated {

	def static void doSetup() {
		new RobotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
