/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractRobotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RobotIdeModule extends AbstractRobotIdeModule {
}
