<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplerobot" nsURI="simplerobot" nsPrefix="simplerobot">
  <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Singleton" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SingletonTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//String"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildWall" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropMark" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeatStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="times" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfElseStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifbody" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsebody" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cond" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atomic" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Full" eSuperTypes="#//Atomic"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mark" eSuperTypes="#//Atomic"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ahead" eSuperTypes="#//Atomic"/>
  <eClassifiers xsi:type="ecore:EClass" name="Heading" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wind" lowerBound="1" eType="#//Orientation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//Atomic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//Expression"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Atomic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" lowerBound="1" eType="#//Atomic"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Orientation">
    <eLiterals name="south"/>
    <eLiterals name="north" value="1"/>
    <eLiterals name="east" value="2"/>
    <eLiterals name="west" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SingletonTypes">
    <eLiterals name="step"/>
    <eLiterals name="turnLeft" value="1"/>
    <eLiterals name="drop" value="2"/>
    <eLiterals name="pick" value="3" literal="pick"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Text" instanceTypeName="Text"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Name" instanceTypeName="Name"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceTypeName="Integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="String">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
