/**
 * generated by Xtext 2.11.0
 */
package org.xtext.scoping;

import org.xtext.scoping.AbstractRobotScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RobotScopeProvider extends AbstractRobotScopeProvider {
}
