/*
 * generated by Xtext 2.11.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.robot.ui.internal.RobotActivator;

public class RobotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotActivator.getInstance().getInjector("org.xtext.Robot");
	}

}
