/**
 * generated by Xtext 2.11.0
 */
package org.xtext;

import org.xtext.AbstractRobotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotRuntimeModule extends AbstractRobotRuntimeModule {
}
